language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-node-module' ]; then cd .. && eval "mv $currentfolder generator-node-module" && cd generator-node-module; fi

